export const themes = {
    dark: `${process.env.PUBLIC_URL}/antd/antd.dark.min.css`,
    light: `${process.env.PUBLIC_URL}/antd/antd.min.css`,
    colors: {
        light: "#FFFFFF",
        primary: "#A2A1FF",
        background: "#252A36",
        primary1: "#C3EDD1",
        dark: "#1D2833",
        primary5: "#00C464",
        neutro5: "#D9D9D9",
        primary400: "#45CE7C",
        danger: "#FF4D4F",
        calendulaGold: "#FFC53D",
        gray: "#4D4D4D",
        submenu: "#818181",
        primary050: "#E6F8EC",
        secondary050: "#E3F2FE",
        subtitle: "#767676",
        late: "#DA2B2B",
        upcoming: "#33A7FF",
    },
};
